export const SHOW_RECOMENDATIONS_MOVIES = 'SHOW_RECOMENDATIONS_MOVIES';

export const GET_POPULAR_MOVIES_START = 'GET_POPULAR_MOVIES_START';
export const GET_POPULAR_MOVIES_SUCCESS = 'GET_POPULAR_MOVIES_SUCCESS';

export const ADD_FAVORITE_MOVIES = 'ADD_FAVORITE_MOVIES';
